//------------------------------------------------------------------------------
// <auto-generated> BusinessObject.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SmallShop.Utilities;

namespace SmallShop.Entities
{
    /// <summary>
    /// 实体类 ExceptionLogInfo
	/// </summary>
    [Serializable]
    public partial class ExceptionLogInfo 
    {	
        /// <summary>
        /// 获取或设置 Id,不可空 
        /// </summary>
        public int Id { get; set; }
		
        /// <summary>
        /// 获取或设置 LoginName,Nulla,长度N20 
        /// </summary>
        public string LoginName { get; set; }
		
        /// <summary>
        /// 获取或设置 Url,可空,长度500 
        /// </summary>
        public string Url { get; set; }
		
        /// <summary>
        /// 获取或设置 Message,可空,长度1000 
        /// </summary>
        public string Message { get; set; }
		
        /// <summary>
        /// 获取或设置 StackTrace,可空,长度-1 
        /// </summary>
        public string StackTrace { get; set; }
		
        /// <summary>
        /// 获取或设置 Ip,不可空,长度20 
        /// </summary>
        public string Ip { get; set; }
		
        /// <summary>
        /// 获取或设置 CreateTime,可空 
        /// </summary>
        public DateTime CreateTime { get; set; }
		
    }
}
