//------------------------------------------------------------------------------
// <auto-generated> BusinessObject.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SmallShop.Utilities;

namespace SmallShop.Entities
{
    /// <summary>
    /// 实体类 OrderItemInfo
	/// </summary>
    [Serializable]
    public partial class OrderItemInfo 
    {	
        /// <summary>
        /// 获取或设置 Id,不可空 
        /// </summary>
        public int Id { get; set; }
		
        /// <summary>
        /// 获取或设置 OrderId,不可空 
        /// </summary>
        public int OrderId { get; set; }
		
        /// <summary>
        /// 获取或设置 Number,可空,长度20 
        /// </summary>
        public string Number { get; set; }
		
        /// <summary>
        /// 获取或设置 ProductId,不可空 
        /// </summary>
        public int ProductId { get; set; }
		
        /// <summary>
        /// 获取或设置 OnlinePrice,可空 
        /// </summary>
        public decimal OnlinePrice { get; set; }
		
        /// <summary>
        /// 获取或设置 SettlementPrice,可空 
        /// </summary>
        public decimal SettlementPrice { get; set; }
		
        /// <summary>
        /// 获取或设置 Copies,不可空 
        /// </summary>
        public int Copies { get; set; }
		
        /// <summary>
        /// 获取或设置 UsedCopies,可空 
        /// </summary>
        public int UsedCopies { get; set; }
		
        /// <summary>
        /// 获取或设置 RefundCopies,可空 
        /// </summary>
        public int RefundCopies { get; set; }
		
        /// <summary>
        /// 获取或设置 Barcode,可空,长度20 
        /// </summary>
        public string Barcode { get; set; }
		
        /// <summary>
        /// 获取或设置 ExpendSolidStartDate,可空 
        /// </summary>
        public DateTime ExpendSolidStartDate { get; set; }
		
        /// <summary>
        /// 获取或设置 ExpendSolidEndDate,可空 
        /// </summary>
        public DateTime ExpendSolidEndDate { get; set; }
		
    }
}
