//------------------------------------------------------------------------------
// <auto-generated> BusinessObject.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SmallShop.Utilities;

namespace SmallShop.Entities
{
    /// <summary>
    /// 实体类 OrderInfo
	/// </summary>
    [Serializable]
    public partial class OrderInfo 
    {	
        /// <summary>
        /// 获取或设置 Id,不可空 
        /// </summary>
        public int Id { get; set; }
		
        /// <summary>
        /// 获取或设置 UserId,可空 
        /// </summary>
        public int UserId { get; set; }
		
        /// <summary>
        /// 获取或设置 Tel,可空,长度11 
        /// </summary>
        public string Tel { get; set; }
		
        /// <summary>
        /// 获取或设置 Ip,不可空,长度20 
        /// </summary>
        public string Ip { get; set; }
		
        /// <summary>
        /// 获取或设置 CreateTime,可空 
        /// </summary>
        public DateTime CreateTime { get; set; }
		
    }
}
