//------------------------------------------------------------------------------
// <auto-generated> BusinessObject.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SmallShop.Utilities;

namespace SmallShop.Entities
{
    /// <summary>
    /// 实体类 RoleUserInfo
	/// </summary>
    [Serializable]
    public partial class RoleUserInfo 
    {	
        /// <summary>
        /// 获取或设置 UserId,不可空 
        /// </summary>
        public int UserId { get; set; }
		
        /// <summary>
        /// 获取或设置 RoleId,不可空 
        /// </summary>
        public int RoleId { get; set; }
		
    }
}
