//------------------------------------------------------------------------------
// <auto-generated> BusinessObject.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SmallShop.Utilities;

namespace SmallShop.Entities
{
    /// <summary>
    /// 实体类 RoleInfo
	/// </summary>
    [Serializable]
    public partial class RoleInfo 
    {	
        /// <summary>
        /// 获取或设置 Id,不可空 
        /// </summary>
        public int Id { get; set; }
		
        /// <summary>
        /// 获取或设置 Name,Nulla,长度N20 
        /// </summary>
        public string Name { get; set; }
		
        /// <summary>
        /// 获取或设置 Permissions,可空,长度4000 
        /// </summary>
        public string Permissions { get; set; }
		
        /// <summary>
        /// 获取或设置 IsInner,可空 
        /// </summary>
        public bool IsInner { get; set; }
		
        /// <summary>
        /// 获取或设置 CreateTime,可空 
        /// </summary>
        public DateTime CreateTime { get; set; }
		
    }
}
