//------------------------------------------------------------------------------
// <auto-generated> BusinessObject.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SmallShop.Utilities;

namespace SmallShop.Entities
{
    /// <summary>
    /// 实体类 UserParentInfo
	/// </summary>
    [Serializable]
    public partial class UserParentInfo 
    {	
        /// <summary>
        /// 获取或设置 UserId,不可空 
        /// </summary>
        public int UserId { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId1,可空 
        /// </summary>
        public int ParentId1 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId2,可空 
        /// </summary>
        public int ParentId2 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId3,可空 
        /// </summary>
        public int ParentId3 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId4,可空 
        /// </summary>
        public int ParentId4 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId5,可空 
        /// </summary>
        public int ParentId5 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId6,可空 
        /// </summary>
        public int ParentId6 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId7,可空 
        /// </summary>
        public int ParentId7 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId8,可空 
        /// </summary>
        public int ParentId8 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId9,可空 
        /// </summary>
        public int ParentId9 { get; set; }
		
        /// <summary>
        /// 获取或设置 ParentId10,可空 
        /// </summary>
        public int ParentId10 { get; set; }
		
    }
}
