//------------------------------------------------------------------------------
// <auto-generated> enityType.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallShop.Entities
{
    /// <summary>
    /// 表示实体.
    /// </summary>
    public enum EntityType
    {
        /// <summary>
        /// ExceptionLog.
        /// </summary>
        ExceptionLog,
		
        /// <summary>
        /// OperationLog.
        /// </summary>
        OperationLog,
		
        /// <summary>
        /// Order.
        /// </summary>
        Order,
		
        /// <summary>
        /// OrderItem.
        /// </summary>
        OrderItem,
		
        /// <summary>
        /// Role.
        /// </summary>
        Role,
		
        /// <summary>
        /// RoleUser.
        /// </summary>
        RoleUser,
		
        /// <summary>
        /// User.
        /// </summary>
        User,
		
        /// <summary>
        /// UserParent.
        /// </summary>
        UserParent,
		
    }
}

