//------------------------------------------------------------------------------
// <auto-generated> enityColumn.cst
//     此代码由工具生成.
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallShop.Entities
{
	#region ExceptionLog
    
    public enum ExceptionLogCols
    {
        
        /// <summary>
        ///Id，不可空
        /// </summary>
        Id, 
        
        /// <summary>
        ///LoginName，Nulla,长度N20
        /// </summary>
        LoginName, 
        
        /// <summary>
        ///Url，可空,长度500
        /// </summary>
        Url, 
        
        /// <summary>
        ///Message，可空,长度1000
        /// </summary>
        Message, 
        
        /// <summary>
        ///StackTrace，可空,长度-1
        /// </summary>
        StackTrace, 
        
        /// <summary>
        ///Ip，不可空,长度20
        /// </summary>
        Ip, 
        
        /// <summary>
        ///CreateTime，可空
        /// </summary>
        CreateTime, 
    }
    
	#endregion
    
	#region OperationLog
    
    public enum OperationLogCols
    {
        
        /// <summary>
        ///Id，不可空
        /// </summary>
        Id, 
        
        /// <summary>
        ///LoginName，Nulla,长度N20
        /// </summary>
        LoginName, 
        
        /// <summary>
        ///Type，不可空
        /// </summary>
        Type, 
        
        /// <summary>
        ///BusinessName，Nulla,长度N50
        /// </summary>
        BusinessName, 
        
        /// <summary>
        ///Description，Nulla,长度N500
        /// </summary>
        Description, 
        
        /// <summary>
        ///Ip，不可空,长度20
        /// </summary>
        Ip, 
        
        /// <summary>
        ///CreateTime，可空
        /// </summary>
        CreateTime, 
    }
    
	#endregion
    
	#region Order
    
    public enum OrderCols
    {
        
        /// <summary>
        ///Id，不可空
        /// </summary>
        Id, 
        
        /// <summary>
        ///UserId，可空
        /// </summary>
        UserId, 
        
        /// <summary>
        ///Tel，可空,长度11
        /// </summary>
        Tel, 
        
        /// <summary>
        ///Ip，不可空,长度20
        /// </summary>
        Ip, 
        
        /// <summary>
        ///CreateTime，可空
        /// </summary>
        CreateTime, 
    }
    
	#endregion
    
	#region OrderItem
    
    public enum OrderItemCols
    {
        
        /// <summary>
        ///Id，不可空
        /// </summary>
        Id, 
        
        /// <summary>
        ///OrderId，不可空
        /// </summary>
        OrderId, 
        
        /// <summary>
        ///Number，可空,长度20
        /// </summary>
        Number, 
        
        /// <summary>
        ///ProductId，不可空
        /// </summary>
        ProductId, 
        
        /// <summary>
        ///OnlinePrice，可空
        /// </summary>
        OnlinePrice, 
        
        /// <summary>
        ///SettlementPrice，可空
        /// </summary>
        SettlementPrice, 
        
        /// <summary>
        ///Copies，不可空
        /// </summary>
        Copies, 
        
        /// <summary>
        ///UsedCopies，可空
        /// </summary>
        UsedCopies, 
        
        /// <summary>
        ///RefundCopies，可空
        /// </summary>
        RefundCopies, 
        
        /// <summary>
        ///Barcode，可空,长度20
        /// </summary>
        Barcode, 
        
        /// <summary>
        ///ExpendSolidStartDate，可空
        /// </summary>
        ExpendSolidStartDate, 
        
        /// <summary>
        ///ExpendSolidEndDate，可空
        /// </summary>
        ExpendSolidEndDate, 
    }
    
	#endregion
    
	#region Role
    
    public enum RoleCols
    {
        
        /// <summary>
        ///Id，不可空
        /// </summary>
        Id, 
        
        /// <summary>
        ///Name，Nulla,长度N20
        /// </summary>
        Name, 
        
        /// <summary>
        ///Permissions，可空,长度4000
        /// </summary>
        Permissions, 
        
        /// <summary>
        ///IsInner，可空
        /// </summary>
        IsInner, 
        
        /// <summary>
        ///CreateTime，可空
        /// </summary>
        CreateTime, 
    }
    
	#endregion
    
	#region RoleUser
    
    public enum RoleUserCols
    {
        
        /// <summary>
        ///UserId，不可空
        /// </summary>
        UserId, 
        
        /// <summary>
        ///RoleId，不可空
        /// </summary>
        RoleId, 
    }
    
	#endregion
    
	#region User
    
    public enum UserCols
    {
        
        /// <summary>
        ///Id，不可空
        /// </summary>
        Id, 
        
        /// <summary>
        ///LoginName，Nulla,长度N20
        /// </summary>
        LoginName, 
        
        /// <summary>
        ///Password，可空,长度32
        /// </summary>
        Password, 
        
        /// <summary>
        ///Type，可空
        /// </summary>
        Type, 
        
        /// <summary>
        ///Balance，可空
        /// </summary>
        Balance, 
        
        /// <summary>
        ///Depth，不可空
        /// </summary>
        Depth, 
        
        /// <summary>
        ///ParentId，可空
        /// </summary>
        ParentId, 
        
        /// <summary>
        ///WeiXinOpenId，可空,长度32
        /// </summary>
        WeiXinOpenId, 
        
        /// <summary>
        ///CreateTime，可空
        /// </summary>
        CreateTime, 
    }
    
	#endregion
    
	#region UserParent
    
    public enum UserParentCols
    {
        
        /// <summary>
        ///UserId，不可空
        /// </summary>
        UserId, 
        
        /// <summary>
        ///ParentId1，可空
        /// </summary>
        ParentId1, 
        
        /// <summary>
        ///ParentId2，可空
        /// </summary>
        ParentId2, 
        
        /// <summary>
        ///ParentId3，可空
        /// </summary>
        ParentId3, 
        
        /// <summary>
        ///ParentId4，可空
        /// </summary>
        ParentId4, 
        
        /// <summary>
        ///ParentId5，可空
        /// </summary>
        ParentId5, 
        
        /// <summary>
        ///ParentId6，可空
        /// </summary>
        ParentId6, 
        
        /// <summary>
        ///ParentId7，可空
        /// </summary>
        ParentId7, 
        
        /// <summary>
        ///ParentId8，可空
        /// </summary>
        ParentId8, 
        
        /// <summary>
        ///ParentId9，可空
        /// </summary>
        ParentId9, 
        
        /// <summary>
        ///ParentId10，可空
        /// </summary>
        ParentId10, 
    }
    
	#endregion
    
}